baseURL: "https://meaculpa.dev/"
languageCode: en-us
title: "meaculpa.dev - driven by curiosity"
theme: "PaperMod"
googleAnalytics: G-JP8WNL0D88

enableRobotsTXT: true
buildDrafts: false
buildFuture: false

googleAnalytics: 

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: about
      name: ABOUT
      url: /about/
      weight: 10
    - identifier: blog
      name: BLOG
      url: /posts/
      weight: 20
    - identifier: projects
      name: PROJECTS
      url: /projects/
      weight: 30
    - identifier: search
      name: SEARCH
      url: /search/
      weight: 40

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideMeta: false
  hideSummary: false
  searchHidden: false
  showToc: true
  tocOpen: true
  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
  label:
    text: "meaculpa.dev"
    #icon: /apple-touch-icon.png
    #iconHeight: 35
  profileMode:
    enabled: true
    title: Dominic Schuld
    subtitle: "~ driven by curiosity ~"
    imageUrl: "me.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: That's me!
    buttons:
      - name: About
        url: about
      - name: Blog
        url: posts
      - name: Projects
        url: projects
  socialIcons:
    - name: github
      url: "https://github.com/meacu1pa"
    - name: twitter
      url: "https://twitter.com/meaculpadev"
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "description", "summary", "content"]
